import antfu from '@antfu/eslint-config';

export default antfu({
  rules: {
    'ts/ban-ts-comment': 'off',
    'node/prefer-global/process': 'off',
    '@typescript-eslint/no-shadow': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    'class-methods-use-this': 'off',
    'default-param-last': 'off',
    'no-param-reassign': 'off',
    'no-console': 'off',
    'no-new-func': 'off',
    'prefer-promise-reject-errors': 'off',
    'require-atomic-updates': 'off',
    'no-plusplus': 'off',
    'no-underscore-dangle': 'off',
    'consistent-return': 'off',
    'no-useless-return': 'off',
    'no-unused-expressions': 'off',
    'max-params': 'off',
    'default-case': 'off',
    'import/no-unresolved': 'off',
    'no-case-declarations': 'off',
    'no-invalid-this': 'off',
    'no-loop-func': 'off',
    'func-names': 'off',
    'no-bitwise': 'off',
    'vue/no-mutating-props': 'off',
    'complexity': 'off',
    'semi': 'warn',
    'arrow-parens': ['warn', 'as-needed'],
    'no-empty': 'off',
    'vue/multi-word-component-names': ['off'],
    'vue/no-setup-props-destructure': ['off'],
    'vue/no-deprecated-slot-attribute': ['off'],
    'vue/no-deprecated-html-element-is': ['off'],
    'vue/no-deprecated-v-on-native-modifier': 'off',
    'no-mixed-spaces-and-tabs': 'off',
    'style/semi': 'off',
    'vue/html-self-closing': 'off',
    'vue/singleline-html-element-content-newline': 'off',
    'style/max-statements-per-line': 'off',
    'regexp/no-super-linear-backtracking': 'off',
    'regexp/no-useless-quantifier': 'off',
    'antfu/if-newline': 'off',
    'unused-imports/no-unused-vars': 'off',
    'style/arrow-parens': 'off',
    'array-callback-return': 'off',
    'style/brace-style': 'off',
    'vue/block-order': [
      'error',
      {
        order: ['template', 'script', 'style'],
      },
    ],
  },
});
